name: On create tag

on:
  release:
    types:
      - published
env:
  GITHUB_TOKEN: ${{ secrets.Test }}

jobs:
  on-create-tag:
    runs-on: ubuntu-latest
    steps:
      # - env:
      #     GITHUB_TOKEN: ${{ secrets.Test }}
      - name: echo
        run: |
          echo hello
