name: On create tag

on:
  push:
    tags:
      - "*"
jobs:
  on-create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo hello
