name: Test

on:
  push:
    branches:
      - "main"

jobs:
  get-dir:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  ls-list:
    runs-on: ubuntu-latest
    steps:
      - name: pwd
        run: |
          pwd
          ls -la
