name: Test

on:
  push:
    branches:
      - "main"

jobs:
  get-dir:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: PyPi fetch
        run: |
          python -m pip install --upgrade pip
          while true; do pip download glob-linters==0.1.0-rc.12; [ $? -eq 0 ] && break || sleep 5; done
