name: On create tag

on:
  workflow_run:
    workflows: ["Release please"]
    types:
      - completed

jobs:
  on-create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo hello
