name: On create tag

on:
  release:
    types:
      - published

env:
  GITHUB_TOKEN: ${{ secrets.TEST }}

jobs:
  on-create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo hello
